blank_issues_enabled: true
issue_template:
  - name: Bug Report
    description: File a bug report
    file: bug_report.yml
  - name: DotCom theme launch checklist
    description: Checklist used to keep track of theme launches on DotCom.
    file: dotcom-theme-launch-checklist.md