name: DotCom theme launch checklist
description: Checklist used to keep track of theme launches on DotCom.
title: '[DotCom Launch]: <theme name>'
body:
    - type: markdown
      attributes:
          value: |
              ### DotCom launch checklist
              - [ ] Test the theme on dotCom
              - [ ] Create demo site
              - [ ] Create theme showcase
              - [ ] Theme launch post
              - [ ] Launch theme

              Remember to add a label to this issue, or creating it if it doesn't exist. Format: [Theme] _<theme name>_
