name: Deploy Themes to Dotorg

on:
  push:
    branches: [ trunk, automate/dotorgdeploy ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./deploy-dotorg.sh preview
