name: Deploy Themes to Dotorg

on:
  push:
    branches: [ trunk ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 
        uses: actions/checkout@v2
        shell: bash
        run: deploy-dotorg.sh preview
        with:
          SVN_USERNAME: ${{secrets.DOTORG_SVN_USERNAME}} 
          SVN_PASSWORD: ${{secrets.DOTORG_SVN_PASSWORD}} 
