name: "Update Themes"

on:
  pull_request:
    types: [ closed ]
    branches:
      - trunk

jobs:
  main:
    if: github.event.pull_request.merged == true
    name: Update changelogs and versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          fetch-depth: "0"
          all_commits: true
          all_tags: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Set Git Identity
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
      - name: Update Theme Versions & Changelogs
        run: |
          npm ci
          npm run update-versions
      - name: Update style.css Files
        run: |
          npm run update-stylecss
          git add . 
          git commit -m "chore:"" auto-update style.css files"
          git push