name: "Update Themes"

on:
  pull_request_target:
    types: [ closed ]
    branches:
      - trunk

jobs:
  main:
    if: github.event.pull_request.merged == true
    name: Update changelogs and versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          fetch-depth: "0"
          all_commits: true
          all_tags: true

      - uses: actions/setup-node@v2
        with:
          node-version: 12
      
      - run: git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: git config --global user.name "github-actions[bot]"
      - run: npm ci
      - run: npm run update-themes
      - run: git add . 
      - run: git commit -m "chore:"" auto-update package info"
      - run: git push
