name: Validate Themes

on:
    pull_request:
        paths:
            - '**/theme.json'
            - '**/styles/*.json'
            - '**/assets/fonts/*.json'
            - '**/style.css'

env:
    PR_PATHS: >-
        '**/theme.json'
        '**/styles/*.json'
        '**/assets/fonts/*.json'
        '**/style.css'
    HUSKY: 0

jobs:
    validate-theme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Validate Themes
              run: node theme-utils.mjs validate-theme $(git diff --name-only HEAD^ -- ${{ env.PR_PATHS }} | awk -F/ '{print $1}' | uniq | paste -s -d, -)
